name: flutter_paygateglobal
version: 0.1.5
homepage: https://pub.dev/packages/flutter_paygateglobal
description: Integrate easily the Paygate Global Platform into your Flutter app.
environment: 
  sdk: '>=2.16.0 <4.0.0'
  flutter: '>=1.17.0'
dependencies: 
  http: ^1.5.0
  flutter: 
    sdk: flutter
  url_launcher: ^6.3.2
dev_dependencies: 
  flutter_lints: ^6.0.0
  flutter_test: 
    sdk: flutter
