name: flutter_paygateglobal
version: 0.1.3
homepage: https://pub.dev/packages/flutter_paygateglobal
#publish_to: https://onepub.dev/api/yonhnoflyg/
description: Integrate easily the Paygate Global Platform into your Flutter app.
environment: 
  sdk: '>=2.16.0 <4.0.0'
  flutter: '>=1.17.0'
dependencies: 
  http: ^1.1.0
  flutter_custom_tabs: ^1.0.4
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter
flutter: null
